### ISSUE TITLE
Text is not visible in dark mode

### ISSUE THREAD

**Issue by zvictor** [on2-dev/share-api-polyfill#120]
Thanks for the great project! It's very useful.

There is an issue for me, though: In my dark-themed application the text is not visible.

It looks like defining a `background-color` but inheriting the text `color` can cause unexpected consequences.
We should either make all the colours dynamic or hard code all of them. A mix is not really a go 🥹

![image](https://user-images.githubusercontent.com/181076/185881948-6912c4fe-265f-4d14-b12e-fe3727068595.png)

![image](https://user-images.githubusercontent.com/181076/185882401-9d4c165a-dbc0-48aa-b688-9b8cf3e98aae.png)

**Comment by felipenmoura** [comment]
Thanks for the PR.y
Also, I believe we can add a `dark mode` support to it (based on user's OS options) or a settings.

I've already merged the PR and will soon publish an update,

**Comment by zvictor** [comment]
That sounds great! thanks!
