### ISSUE TITLE
Add support to a new idiom: Hindi

### ISSUE THREAD

**Issue by rsip22** [on2-dev/share-api-polyfill#134]
Currently supported languages:
- cs
- de
- it
- da
- en
- es
- fr
- hu
- is
- ja
- ko
- nl
- ta
- pl
- pt
- ru
- sv
- sk
- tr
- zh

Add support to a new language!

**Comment by abhishak3** [comment]
I'd like to add support for Hindi. Please assign this issue to me.

**Comment by rsip22** [comment]
That would be great, @abhishak3! Thanks for volunteering!

**Comment by rsip22** [comment]
Closed #140

**Comment by rsip22** [comment]
Closed #140
