### ISSUE TITLE
Transpile the code in order to get iOS 10 support

### ISSUE THREAD

**Issue by dimaip** [on2-dev/share-api-polyfill#48]
The package uses spread in a couple of places, and it's not transpiled, thus iOS 10 fails with 

```
Unexpected token '...'. Expected a property name.
```

**Comment by felipenmoura** [comment]
Hm, I don't have an iOS device to test it!
But the strange thing is that we do transpile the code! We use gulp to build it.
Can you give us more details?

**Comment by dimaip** [comment]
Hey sure @felipenmoura, have a look here, spread is not transpiled: https://github.com/on2-dev/share-api-polyfill/blob/main/dist/share.js#L206
