### ISSUE TITLE
Add LINE

### ISSUE THREAD

**Issue by StorytellerCZ** [on2-dev/share-api-polyfill#52]
LINE is a messenger like app that is especially popular in Japan.

https://line.me/en-US/

Sharing documentation:
https://social-plugins.line.me/en/

Icon on Font Awesome:
https://fontawesome.com/icons/line?style=brands

**Comment by rsip22** [comment]
Hello, @StorytellerCZ !

I am not familiar with LINE. The proposed target would be something like this?

![image](https://user-images.githubusercontent.com/16676222/193392392-48483b32-62e7-42d0-9f7a-1825999462ad.png)

**Comment by StorytellerCZ** [comment]
It's been a while. Looking at my current implementation the URL is: `https://social-plugins.line.me/lineit/share?url=${encodedUrl}&text=${text}`

**Comment by rsip22** [comment]
Closed with  PR #150
