### ISSUE TITLE
URL-encoding for Twitter 

### ISSUE THREAD

**Issue by MalgoBlock** [on2-dev/share-api-polyfill#76]
I have noticed that using special characters inside the shared text breaks links for Twitter (on desktop). (For example: '|')
The characters are passed straight into the link and Twitter has a problem with decoding it.
Unfortunately using URL-encode value (for example '%7C') in the text string makes it work for Twitter but then on Facebook & WhatsApp the code is displayed instead of the required character. (eg. 'my text %7C ....')
Only Telegram works fine with both ways.
I only test on Facebook, WhatsApp, Twitter and Telegram as I don't use other sharing options.

Wrapping my text in encodeURIComponent makes it work for Twitter but the Facebook and WhatsApp text doesn't work as it gets encoded twice. 
I think this would solve the problem:
```
case 'twitter': {
    window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${url}&hashtags=${hashtags || ''}`);
    break;
}
```

**Comment by valentinoli** [comment]
I guess this issue can be closed now, proposed changes have been merged
